Repository octokit/endpoint.js, pull requests merged in 2023-06, with the labels that each got.

#421 fix(build): switch to esbuild instead of pika
  package-lock.json
  package.json
  scripts/build.mjs
  src/defaults.ts
  src/endpoint-with-defaults.ts
  src/merge.ts
  src/parse.ts
  src/with-defaults.ts
  test/parse.test.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#388 feat: remove previews logic
  README.md
  package-lock.json
  package.json
  src/defaults.ts
  src/merge.ts
  src/parse.ts
  test/defaults.test.ts
  test/endpoint.test.ts
  test/merge.test.ts
  test/parse.test.ts
Labels: Type: Maintenance, Type: Breaking change

#424 ci(release): enable releases for beta, and maintencance releases
  .github/workflows/release.yml
Labels: Type: Maintenance

#418 feat: v8
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  scripts/build.mjs
  src/defaults.ts
  src/merge.ts
  src/parse.ts
  test/defaults.test.ts
  test/endpoint.test.ts
  test/merge.test.ts
  test/parse.test.ts
Labels: Type: Breaking change, Type: Feature

#426 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation

#427 fix: account for possibility that `mergedOptions.mediaType.previews` may be undefined
  src/merge.ts
  test/endpoint.test.ts
Labels: Type: Bug
