Repository octokit/endpoint.js, pull requests merged in 2023-01, with the labels that each got.

#387 Avoid triggering codeql on push events to dependabot PRs
  .github/workflows/codeql.yml
Labels: Type: Maintenance, Priority: Normal

#392 Default branch rename
  .github/pull_request_template.md
  .github/workflows/release.yml
  .github/workflows/test.yml
  README.md
  package.json
Labels: Type: Maintenance

#382 fix: type cast empty array to fix a typescript error
  src/parse.ts
Labels: Type: Bug
